version: 2
updates:
  - package-ecosystem: npm
    directory: /
    open-pull-requests-limit: 999
    rebase-strategy: disabled
    versioning-strategy: increase
    schedule:
      interval: weekly
    cooldown:
      default-days: 7
    labels:
      - dependencies
    groups:
      vitest:
        patterns:
          - "vitest"
          - "@vitest/*"
  - package-ecosystem: github-actions
    directory: /
    open-pull-requests-limit: 999
    rebase-strategy: disabled
    schedule:
      interval: weekly
    cooldown:
      default-days: 7
    labels:
      - dependencies
  - package-ecosystem: bundler
    directory: ./docs
    open-pull-requests-limit: 999
    rebase-strategy: disabled
    schedule:
      interval: weekly
    cooldown:
      default-days: 7
    labels:
      - dependencies
