version: 2
updates:
  - package-ecosystem: npm
    directory: /
    open-pull-requests-limit: 999
    rebase-strategy: disabled
    schedule:
      interval: weekly
    labels:
      - dependencies
    ignore:
      - dependency-name: eslint-config-mourner
        update-types: ["version-update:semver-major"]
      - dependency-name: sinon
        update-types: ["version-update:semver-major"]
      - dependency-name: mocha
        update-types: ["version-update:semver-major"]
  - package-ecosystem: "github-actions"
    directory: "/"
    open-pull-requests-limit: 999
    rebase-strategy: disabled
    schedule:
      interval: weekly
    labels:
      - dependencies
