version: 2
updates:
  - package-ecosystem: npm
    directory: /
    open-pull-requests-limit: 999
    rebase-strategy: disabled
    schedule:
      interval: weekly
    labels:
      - dependencies
  - package-ecosystem: github-actions
    directory: /
    open-pull-requests-limit: 999
    rebase-strategy: disabled
    schedule:
      interval: weekly
    labels:
      - dependencies
  - package-ecosystem: bundler
    directory: ./docs
    open-pull-requests-limit: 999
    rebase-strategy: disabled
    schedule:
      interval: weekly
    labels:
      - dependencies
