blank_issues_enabled: true
contact_links:
  - name: Support
    url: https://stackoverflow.com/questions/tagged/leaflet
    about: >
      We use GitHub as an issue tracker and do not provide support here.
      For general usage please refer to the Leaflet documentation:
      https://leafletjs.com.
      For support questions like "How can I do X with Leaflet?"
      please search or ask questions on
      StackOverflow: https://stackoverflow.com/questions/tagged/leaflet or
      StackExchange: https://gis.stackexchange.com/questions/tagged/leaflet.
