name: Feature request
description: Suggest an idea for this project
labels: ["feature", "needs triage"]
body:
  - type: checkboxes
    attributes:
      label: Checklist
      description: >
        Please confirm the following:
      options:
        - label: I've searched through the [plugins](https://leafletjs.com/plugins.html) to make sure this feature isn't already available, or think it shouldn't require a plugin.
          required: false
        - label: I've searched through the [current issues](https://github.com/Leaflet/Leaflet/issues) to make sure this feature hasn't been requested already.
          required: false
        - label: I agree to follow the [Code of Conduct](https://github.com/Leaflet/Leaflet/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
          required: true

  - type: textarea
    attributes:
      label: Motivation
      description: >
        Is your feature request related to a problem? Provide a clear and concise description of what the problem is.
        Provide additional context if necessary (screenshots, video, links, etc.).
      placeholder: >
        e.g. "I'm always frustrated when [...]"
    validations:
      required: true

  - type: textarea
    attributes:
      label: Suggested solution
      description: >
        Provide a clear and concise description of what you want to happen.
        Provide additional context if necessary (screenshots, video, links, etc.).
    validations:
      required: true

  - type: textarea
    attributes:
      label: Alternatives considered
      description: >
        Please describe any alternative solutions or features you've considered.
    validations:
      required: false
