{
	"browser": true,
	"node": true,
	"predef": ["define", "L", "expect", "describe", "it", "sinon", "happen", "beforeEach", "afterEach"],
	"strict": false,
	"bitwise": true,
	"camelcase": true,
	"curly": true,
	"eqeqeq": true,
	"forin": false,
	"immed": true,
	"latedef": true,
	"newcap": true,
	"noarg": true,
	"noempty": true,
	"nonew": true,
	"undef": true,
	// "unused": true,
	// "quotmark": "single",
	"indent": 4,
	"trailing": true,
	"white": true,
	"smarttabs": true
	// "maxlen": 120
}
