name: Artifacts
on:
  push:
    branches: master
    tags: v*
jobs:
  upload:
    runs-on: ubuntu-latest
    if: secrets.AWS_S3_BUCKET && secrets.AWS_ACCESS_KEY_ID && secrets.AWS_SECRET_ACCESS_KEY
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: 16
          check-latest: true
          cache: npm

      - name: Install dependencies
        run: npm ci
      - run: npm run build

      - name: Compress artifacts
        working-directory: dist
        run: zip -r leaflet.zip .

      - name: Determine directory for artifacts
        id: artifacts-directory
        run: |
          VERSION=$(git tag --points-at HEAD)
          echo "::set-output name=path::content/leaflet/${VERSION:-master}"

      - name: Deploy artifacts
        uses: jakejarvis/s3-sync-action@v0.5.1
        with:
          args: --acl public-read --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SOURCE_DIR: dist
          DEST_DIR: ${{ steps.artifacts-directory.outputs.path }}
